[package]
name = "plutus_data"
version = "0.0.6"
edition = "2021"
authors = ["Olof Blomqvist <olof@twnet.se>"]
description = "derive macros for converting between rust data types and plutus-data"
repository = "https://github.com/OlofBlomqvist/plutus_data"
license-file = "licence"

[dependencies]
plutus_data_derive = "0.0.5"
#plutus_data_derive = { path = "../plutus_data_derive" }
cardano-multiplatform-lib = {path="../cml/rust",features=["wasm"]}
hex = "^0.4.3"



